services:
  # Frontend (React app with Vite)
  - name: pesticidepro-frontend
    type: web
    env: static
    staticPublishPath: client/dist
    buildCommand: cd client && npm install && npm run build

  # Backend (Node.js with TypeScript & Google Sheets API)
  - name: pesticidepro-backend
    type: web
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: GOOGLE_SHEET_ID
        value: 19emAWfw4K7EmKceauFVq7zzpOXsNV03iCneadthpnLs
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        value: pesticidecalculator@pesticidecalculator.iam.gserviceaccount.com
      - key: GOOGLE_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxVpbMYcMgMWnj\n31sJrrsnjN8lgu28weR1Vm20KgO1/vcQgt4fhShMhowWwngdA7kpEcSKTadN8u/L\nFA0MqC/fSc9zlh9xmSu+0Moa5AaBB/z0f1CDuGo0NW/WkKVLw4zyNhMXVzossWa6\nwWURMAWY1Gh5k90L5w5ipNuJUdx69fzdUDX0mLLBKOM4QDQHZg1tGG6J8PKQkBlZ\nxaT9/DO9hc1AIkiilNaOFaOOrK6cRtDwENRV4XvINLDvkZEd2+LEhs/u4b5E0tXk\nXWVrlXeEMVFsVp7Gt1tG5Xuj7ehVyWbbweLf1M25XDj/nb3sV/RH2GrvC6iHGAp2\nPzn7RbqdAgMBAAECggEAJIZ3WkKzgAy1aN3+3/Rpb0i0SENaiHNuBN3njAFQUNqi\nE/hEXD0ekv5uWZy1xRIYf7U9ZBgA4szr50mqs2XrsEOBUycDNHBOIofZ7KZ1EXvt\n9YTIdkzUMQsljQ2vQfbVr6iED51jacOjK0l8cckQig0LtKjIETTGkXovjm26Kefq\n+Ch9HngOW0SqKvOwgH70RxdC1n6OhYOev//n13CsqUKGZ78dP5UVehLLxwGiuv54\nzNdWFDuik2tVI4awvGwCXk/oAGG5b3PTFD58JChk/a6szsxpfUUH/Xg48WR5pf9N\nDnv01POjlRdl8JR0RJGNjgfWdEp4Wxxj/YrTDtjgSQKBgQDjR2fYqxeed3NUJeDJ\nbnu0j5W2j/1JDUZ3PUPctcLinL/AW6ThSag2NLPERHPVEf13fjuKdeakWxjnAXp8\nzwDKrHtovRb25EXbXT1ByO5+QpzdZsWM4OJnDzbD6fJctJOJhSaZceaiQg6P8Tq1\nk1puz41cWfRM65TY87JvkUYpaQKBgQDHv5NT4sUbVj/sHSl5kSeXPKjOrFLW/s1P\nVaHyK5EcVFxcx3tcOtpj1kTo/WA2dqruLgZCQRaWONio2i83o3OBFJU4CBGSGsuy\nWVA3/fXo35Krr43oHkXGOyia+QU9oB7warbk/YNsGb4Ypi7v/t66ic4YFhwVClPW\n7XnMtdoNFQKBgBw2Nd7ARhtGiotMdF2smDBujk/uCauyuSd99FmGOl20xVyUQ6Av\na3DnE9VuBc7R/9uAUNW8Etgd8rZiCZlKfLert1nl9t7IsR8ssLjkvy3vCNe2tRjq\npU/TpKGm/Y2iYJn2bDcp204S0wntELOPSe9tVge7psaRi5VukpyktMfZAoGBAJ0y\nb0d9F5HD9tpiuNkrGvUyj8bWZvs722esBJ8JGlIpMebyNmsHBge8AM87WBSEn1CC\nd/p8LsJaSmfYDYDD6YqUIDrQXsOUwunA0BjAjF6QVGU463zZFiBDPll30GAHO1IJ\nKZZczKiuOaQ8ZIQLGE3FVaQvAjqsvf5PNaOdGdVhAoGANJJC0F0aneCWUd5nSS5W\n3L6geylpF0e6EfgQpOhrG82Pg01iiLf1t6fFVyUdw7uuc4jViG3C7xrzy04bWVp1\njNmu/waxQkKpIZ/O5GdG4ZJOefO0XAFucx92NqsIqCBz3+McWSUohum0c84YM6iR\nxZEx5LmZfDnFn4OJFtQpAak=\n-----END PRIVATE KEY-----\n"
